version: '3'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: db
      PGDATA: /tmp
    ports: 
      - "3306:3306"
    volumes:
      - db-data/var/lib/postgresql/data
  web:
    build: .
    environment:
      SECRET_KEY_BASE: "${KEY}"
    command: bundle exec rails s -b '0.0.0.0'
    volumes:
      - .:/shopify_task_api
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db-data:
    driver: local
  bundle:
    driver: local